apiVersion: apps/v1
kind: Deployment
metadata:
  name:  vue-testapp
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  vue-testapp
  template:
    metadata:
      labels:
        app:  vue-testapp
    spec:
      containers:
        - name:  vue-webapp
          image: obike007/vue:webapp
          ports:
            - containerPort: 80 
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /etc/test
            name: test-mnty
      volumes:
      - name: test-mnty
        hostPath:
          path: /etc/vue
          type: Directory
         
      
