#Default location is /etc/ansible/hosts 
all:
  vars:
    ansible_user: "ansible" 
    ansible_password: '{{ lookup("env", "ANSIBLE_PASSWORD") }}'
debian:
  hosts:
    ubuntu1:
    ubuntu2:
    ubuntu3: 
centos:
  hosts:
    centos1:
    centos2:
    centos3:

