#Default location is /etc/ansible/hosts 
ansible_user: "ansible" 
ansible_password: "password"
debian:
  hosts:
    ubuntu1:
    ubuntu2:
    ubuntu3: 
centos:
  hosts:
    centos1:
    centos2:
    centos3:

