name: workflows

on:
  push:
    branches:
      - master
build_docker_image:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
  script:
    - echo "Generated image tag is $IMAGE_TAG"
    - docker build -t obike007/vue:webapp-${{ github.sha }} .
push_docker_image:
  stage: push
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
    - docker push obike007/vue:webapp-${{ github.sha }} .
    #- docker rmi giddy87/vue:webapp-${{ github.sha }} .

deploy_to_dev:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
  environment: dev
  before_script:
    - git config --global user.email "pipeline_user@thebulb.com"
    - git config --global user.name "pipeline"
  script:
    - git remote set-url origin http://${PIPELINE_TOKEN}@localhost/root/gitops.git
    - git clone http://pipeline:${PIPELINE_TOKEN}@localhost/root/gitops.git
    - cd gitops
    - sed -i 's/vue:webapp-.*/'vue:webapp-"$${{ github.sha }} ."'/g' dev/deployment.yaml
    - cat dev/deployment.yaml
    - git add dev/deployment.yaml
    - git commit -m "Updated vue test app Dev env k8s manifest files"
    - git push
